version: '3.1'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container_abstract
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # Use a secure password
      MYSQL_DATABASE: admin_db # Database to be created automatically
      MYSQL_USER: admin # Admin username
      MYSQL_PASSWORD: adminpassword # Admin password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d # Initialization scripts
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_abstract
    environment:
      PMA_HOST: mysql # Use the service name of MySQL as the host
      PMA_PORT: 3306
      PMA_USER: admin # Optional: For auto-login in phpMyAdmin
      PMA_PASSWORD: adminpassword # Optional: For auto-login in phpMyAdmin
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
